In [60]:
import numpy as np
import pandas as pd
import acquire

In [61]:
df = acquire.get_telco_data()

# Prepare vs Clean

In [ ]:
# Prepare.py

# 1. - Explore -
# clean()

# 2. - Prepare -
# train_val_test()

# 3. - Model - 
# Xtrain_ytrain()

In [62]:
df.head(1).T

                                            0
customer_id                        0002-ORFBO
contract_type_id                            2
payment_type_id                             2
internet_service_type_id                    1
gender                                 Female
senior_citizen                              0
partner                                   Yes
dependents                                Yes
tenure                                      9
phone_service                             Yes
multiple_lines                             No
online_security                            No
online_backup                             Yes
device_protection                          No
tech_support                              Yes
streaming_tv                              Yes
streaming_movies                           No
paperless_billing                         Yes
monthly_charges                          65.6
total_charges                           593.3
churn                                      No
internet_service_type                     DSL
phone_service                             Yes
multiple_lines                             No
internet_service_type_id                    1
online_security                            No
online_backup                             Yes
device_protection                          No
tech_support                              Yes
streaming_tv                              Yes
streaming_movies                           No
payment_type                     Mailed check
contract_type                        One year
churn_month                              None
contract_type_id                            2
paperless_billing                         Yes
gender                                 Female
senior_citizen                              0
partner                                   Yes
dependents                                Yes
payment_type_id                             2
monthly_charges                          65.6
total_charges                           593.3
signup_date               2021-04-21 18:07:34

# 1 - Drop Redundant Columns

In [63]:
# Dropped Redundant Columns
df = df.drop(['payment_type_id','internet_service_type_id','contract_type_id'],axis=1)

In [101]:
# First column should be `customer_id` after dropping other redudant columns
df.columns.tolist()[0] == 'customer_id'

True

In [ ]:
df['gender_encoded'] = df.gender.map({'Female': 1, 'Male': 0})
df['partner_encoded'] = df.partner.map({'Yes': 1, 'No': 0})
df['dependents_encoded'] = df.dependents.map({'Yes': 1, 'No': 0})
df['phone_service_encoded'] = df.phone_service.map({'Yes': 1, 'No': 0})
df['paperless_billing_encoded'] = df.paperless_billing.map({'Yes': 1, 'No': 0})
df['churn_encoded'] = df.churn.map({'Yes': 1, 'No': 0})

In [ ]:
dummy_df = pd.get_dummies(df[['multiple_lines', \
                              'online_security', \
                              'online_backup', \
                              'device_protection', \
                              'tech_support', \
                              'streaming_tv', \
                              'streaming_movies', \
                              'contract_type', \
                              'internet_service_type', \
                              'payment_type']], dummy_na=False, \
                              drop_first=True)

In [ ]:
imputer = SimpleImputer(missing_values = np.nan, strategy='most_frequent')
train[['embark_town']] = imputer.fit_transform(train[['embark_town']])
validate[['embark_town']] = imputer.transform(validate[['embark_town']])
test[['embark_town']] = imputer.transform(test[['embark_town']])

In [65]:
# Total Columns
df.shape[1]

38

In [66]:
df.head(1).T

                                         0
customer_id                     0002-ORFBO
gender                              Female
senior_citizen                           0
partner                                Yes
dependents                             Yes
tenure                                   9
phone_service                          Yes
multiple_lines                          No
online_security                         No
online_backup                          Yes
device_protection                       No
tech_support                           Yes
streaming_tv                           Yes
streaming_movies                        No
paperless_billing                      Yes
monthly_charges                       65.6
total_charges                        593.3
churn                                   No
internet_service_type                  DSL
phone_service                          Yes
multiple_lines                          No
online_security                         No
online_backup                          Yes
device_protection                       No
tech_support                           Yes
streaming_tv                           Yes
streaming_movies                        No
payment_type                  Mailed check
contract_type                     One year
churn_month                           None
paperless_billing                      Yes
gender                              Female
senior_citizen                           0
partner                                Yes
dependents                             Yes
monthly_charges                       65.6
total_charges                        593.3
signup_date            2021-04-21 18:07:34

In [67]:
df.dtypes

customer_id                      object
gender                           object
senior_citizen                    int64
partner                          object
dependents                       object
tenure                            int64
phone_service                    object
multiple_lines                   object
online_security                  object
online_backup                    object
device_protection                object
tech_support                     object
streaming_tv                     object
streaming_movies                 object
paperless_billing                object
monthly_charges                 float64
total_charges                    object
churn                            object
internet_service_type            object
phone_service                    object
multiple_lines                   object
online_security                  object
online_backup                    object
device_protection                object
tech_support                     object
streaming_tv                     object
streaming_movies                 object
payment_type                     object
contract_type                    object
churn_month                      object
paperless_billing                object
gender                           object
senior_citizen                    int64
partner                          object
dependents                       object
monthly_charges                 float64
total_charges                    object
signup_date              datetime64[ns]
dtype: object

# 2. Fix `total_charges` - From `object` to `int`

In [ ]:
# Fix incoming dataframe column with numerical values set as string type
df['total_charges'] = (df.total_charges + '0').astype('float')

In [69]:
df.dtypes

customer_id                      object
gender                           object
senior_citizen                    int64
partner                          object
dependents                       object
tenure                            int64
phone_service                    object
multiple_lines                   object
online_security                  object
online_backup                    object
device_protection                object
tech_support                     object
streaming_tv                     object
streaming_movies                 object
paperless_billing                object
monthly_charges                 float64
total_charges                   float64
churn                            object
internet_service_type            object
phone_service                    object
multiple_lines                   object
online_security                  object
online_backup                    object
device_protection                object
tech_support                     object
streaming_tv                     object
streaming_movies                 object
payment_type                     object
contract_type                    object
churn_month                      object
paperless_billing                object
gender                           object
senior_citizen                    int64
partner                          object
dependents                       object
monthly_charges                 float64
total_charges                   float64
signup_date              datetime64[ns]
dtype: object

In [70]:
len(df.columns)

38

In [72]:
df.isnull().sum()

customer_id                 0
gender                      0
senior_citizen              0
partner                     0
dependents                  0
tenure                      0
phone_service               0
multiple_lines              0
online_security             0
online_backup               0
device_protection           0
tech_support                0
streaming_tv                0
streaming_movies            0
paperless_billing           0
monthly_charges             0
total_charges               0
churn                       0
internet_service_type       0
phone_service               0
multiple_lines              0
online_security             0
online_backup               0
device_protection           0
tech_support                0
streaming_tv                0
streaming_movies            0
payment_type                0
contract_type               0
churn_month              5174
paperless_billing           0
gender                      0
senior_citizen              0
partner                     0
dependents                  0
monthly_charges             0
total_charges               0
signup_date                 0
dtype: int64

In [75]:
churn_info = df[['churn_month','customer_id','churn']]

In [76]:
df = df.drop(['churn_month'],axis=1)

In [77]:
df.head(1).T

                                         0
customer_id                     0002-ORFBO
gender                              Female
senior_citizen                           0
partner                                Yes
dependents                             Yes
tenure                                   9
phone_service                          Yes
multiple_lines                          No
online_security                         No
online_backup                          Yes
device_protection                       No
tech_support                           Yes
streaming_tv                           Yes
streaming_movies                        No
paperless_billing                      Yes
monthly_charges                       65.6
total_charges                        593.3
churn                                   No
internet_service_type                  DSL
phone_service                          Yes
multiple_lines                          No
online_security                         No
online_backup                          Yes
device_protection                       No
tech_support                           Yes
streaming_tv                           Yes
streaming_movies                        No
payment_type                  Mailed check
contract_type                     One year
paperless_billing                      Yes
gender                              Female
senior_citizen                           0
partner                                Yes
dependents                             Yes
monthly_charges                       65.6
total_charges                        593.3
signup_date            2021-04-21 18:07:34

In [79]:
df.isnull().sum()

customer_id              0
gender                   0
senior_citizen           0
partner                  0
dependents               0
tenure                   0
phone_service            0
multiple_lines           0
online_security          0
online_backup            0
device_protection        0
tech_support             0
streaming_tv             0
streaming_movies         0
paperless_billing        0
monthly_charges          0
total_charges            0
churn                    0
internet_service_type    0
phone_service            0
multiple_lines           0
online_security          0
online_backup            0
device_protection        0
tech_support             0
streaming_tv             0
streaming_movies         0
payment_type             0
contract_type            0
paperless_billing        0
gender                   0
senior_citizen           0
partner                  0
dependents               0
monthly_charges          0
total_charges            0
signup_date              0
dtype: int64

# 3. Remove Duplicate Columns

In [ ]:
# Removed Duplicate Columns
# Due to Multiple Table Joins

```python
'''
df.columns.duplicated() returns a boolean array: a True or False for each column. If it is False then the column name is unique up to that point, if it is True then the column name is duplicated earlier. For example, using the given example, the returned value would be [False,False,True].

Pandas allows one to index using boolean values whereby it selects only the True values. Since we want to keep the unduplicated columns, we need the above boolean array to be flipped (ie [True, True, False] = ~[False,False,True])

Finally, df.loc[:,[True,True,False]] selects only the non-duplicated columns using the aforementioned indexing capability.

The final .copy() is there to copy the dataframe to (mostly) avoid getting errors about trying to modify an existing dataframe later down the line.
'''
```

In [80]:
df = df.loc[:,~df.columns.duplicated()].copy()

In [81]:
len(df.columns)

22

In [82]:
# Temporary list with only names of categorical columns from incoming dataframe
categorical_columns = df.drop(columns = 'customer_id').select_dtypes(include=object).columns.to_list()

In [83]:
categorical_columns

['gender',
 'partner',
 'dependents',
 'phone_service',
 'multiple_lines',
 'online_security',
 'online_backup',
 'device_protection',
 'tech_support',
 'streaming_tv',
 'streaming_movies',
 'paperless_billing',
 'churn',
 'internet_service_type',
 'payment_type',
 'contract_type']

In [84]:
categorical_columns_binary = []

for i in range(len(categorical_columns)):
        if len(df[categorical_columns[i]].value_counts()) == 2:
            categorical_columns_binary.append(categorical_columns[i])

In [85]:
categorical_columns_binary

['gender',
 'partner',
 'dependents',
 'phone_service',
 'paperless_billing',
 'churn']

In [86]:
categorical_columns_binary_dummies = pd.get_dummies(df[categorical_columns_binary],drop_first=True)

In [87]:
categorical_columns_binary_dummies.head(1)

,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,paperless_billing_Yes,churn_Yes
0,0,1,1,1,1,0

In [88]:
categorical_columns_not_binary = []
for i in range(len(categorical_columns)):
        if len(df[categorical_columns[i]].value_counts()) > 2:
            categorical_columns_not_binary.append(categorical_columns[i])

In [89]:
categorical_columns_not_binary

['multiple_lines',
 'online_security',
 'online_backup',
 'device_protection',
 'tech_support',
 'streaming_tv',
 'streaming_movies',
 'internet_service_type',
 'payment_type',
 'contract_type']

In [90]:
categorical_columns_not_binary_dummies = pd.get_dummies(df[categorical_columns_not_binary],drop_first=True)

In [91]:
categorical_columns_not_binary_dummies

,multiple_lines_No phone service,multiple_lines_Yes,online_security_No internet service,online_security_Yes,online_backup_No internet service,online_backup_Yes,device_protection_No internet service,device_protection_Yes,tech_support_No internet service,tech_support_Yes,...,streaming_tv_Yes,streaming_movies_No internet service,streaming_movies_Yes,internet_service_type_Fiber optic,internet_service_type_None,payment_type_Credit card (automatic),payment_type_Electronic check,payment_type_Mailed check,contract_type_One year,contract_type_Two year
0,0,0,0,0,0,1,0,0,0,1,...,1,0,0,0,0,0,0,1,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
3,0,0,0,0,0,1,0,1,0,0,...,1,0,1,1,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,0,0,0,1,0,0,0,0,...,1,0,1,1,0,0,0,1,1,0
7039,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
7040,0,0,1,0,1,0,1,0,1,0,...,0,1,0,0,1,0,0,0,0,0
7041,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7042,1,0,0,1,0,1,0,1,0,0,...,1,0,1,0,0,0,1,0,0,1

In [92]:
df = pd.concat([df, categorical_columns_binary_dummies], axis=1)
df = pd.concat([df, categorical_columns_not_binary_dummies], axis=1)

In [93]:
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'paperless_billing', 'monthly_charges',
       'total_charges', 'churn', 'internet_service_type', 'payment_type',
       'contract_type', 'signup_date', 'gender_Male', 'partner_Yes',
       'dependents_Yes', 'phone_service_Yes', 'paperless_billing_Yes',
       'churn_Yes', 'multiple_lines_No phone service', 'multiple_lines_Yes',
       'online_security_No internet service', 'online_security_Yes',
       'online_backup_No internet service', 'online_backup_Yes',
       'device_protection_No internet service', 'device_protection_Yes',
       'tech_support_No internet service', 'tech_support_Yes',
       'streaming_tv_No internet service', 'streaming_tv_Yes',
       'streaming_movies_No internet service', 'streaming_movies_Yes',
       'internet_service_type_Fiber optic', 'internet_service_type_None',
       'payment_type_Credit card (automatic)', 'payment_type_Electronic check',
       'payment_type_Mailed check', 'contract_type_One year',
       'contract_type_Two year'],
      dtype='object')

In [94]:
df.head(1).T

                                                         0
customer_id                                     0002-ORFBO
gender                                              Female
senior_citizen                                           0
partner                                                Yes
dependents                                             Yes
tenure                                                   9
phone_service                                          Yes
multiple_lines                                          No
online_security                                         No
online_backup                                          Yes
device_protection                                       No
tech_support                                           Yes
streaming_tv                                           Yes
streaming_movies                                        No
paperless_billing                                      Yes
monthly_charges                                       65.6
total_charges                                        593.3
churn                                                   No
internet_service_type                                  DSL
payment_type                                  Mailed check
contract_type                                     One year
signup_date                            2021-04-21 18:07:34
gender_Male                                              0
partner_Yes                                              1
dependents_Yes                                           1
phone_service_Yes                                        1
paperless_billing_Yes                                    1
churn_Yes                                                0
multiple_lines_No phone service                          0
multiple_lines_Yes                                       0
online_security_No internet service                      0
online_security_Yes                                      0
online_backup_No internet service                        0
online_backup_Yes                                        1
device_protection_No internet service                    0
device_protection_Yes                                    0
tech_support_No internet service                         0
tech_support_Yes                                         1
streaming_tv_No internet service                         0
streaming_tv_Yes                                         1
streaming_movies_No internet service                     0
streaming_movies_Yes                                     0
internet_service_type_Fiber optic                        0
internet_service_type_None                               0
payment_type_Credit card (automatic)                     0
payment_type_Electronic check                            0
payment_type_Mailed check                                1
contract_type_One year                                   1
contract_type_Two year                                   0

In [98]:
type(churn_info)

pandas.core.frame.DataFrame

In [99]:
churn_info['signup_date']=df[['signup_date']]

In [100]:
churn_info

     churn_month customer_id churn         signup_date
0           None  0002-ORFBO    No 2021-04-21 18:07:34
1           None  0003-MKNFE    No 2021-04-21 18:07:34
2     2022-01-31  0004-TLHLJ   Yes 2021-09-21 18:07:34
3     2022-01-31  0011-IGKFF   Yes 2020-12-21 18:07:34
4     2022-01-31  0013-EXCHZ   Yes 2021-10-21 18:07:34
...          ...         ...   ...                 ...
7038        None  9979-RGMZT    No 2021-06-21 18:07:34
7039  2022-01-31  9985-MWVIX   Yes 2021-12-21 18:07:34
7040  2022-01-31  9986-BONCE   Yes 2021-09-21 18:07:34
7041        None  9992-UJOEL    No 2021-11-21 18:07:34
7042        None  9995-HOTOH    No 2016-10-21 18:07:34

[7043 rows x 4 columns]

In [ ]:
# Prepare.py

# 1. - Explore -
# clean()

# 2. - Prepare -
# train_val_test()

# 3. - Model - 
# Xtrain_ytrain()

# Final Function

In [ ]:
def prep_telco(df):
    '''
    
    accepts Telco Churn Dataframe
    
    Fixes numerical column 'total_charges' in wrong data type, drops unused columns,
    creates dummy columns of categorical values (sorts bivariate & multivariate), and
    concatenates temporary variables holding 2 types of dummies to main dataframe
    
    
    '''
    
    # Fix incoming dataframe column with numerical values set as string type
    df['total_charges'] = (df.total_charges + '0').astype('float')
    
    # Remove useless columns from incoming dataframe
    df = df.drop(columns = ['internet_service_type_id', 'contract_type_id', 'payment_type_id'])
    
    # Remove duplicate columns
    df = df.loc[:,~df.columns.duplicated()].copy()
    
    # Temporary list with only names of categorical columns from incoming dataframe
    categorical_columns = df.drop(columns = 'customer_id').select_dtypes(include=object).columns.to_list()

    # Filtering list into 1 of 2 types of categorical columns:
    # e.g. BIVARIATE
    #-------------------------------------------------------------------------------------------------------
    
    # Empty list to hold categorical columns with BIVARIATE values
    categorical_columns_binary = []

    # Loop to search binary values in categorical column
    for i in range(len(categorical_columns)):
        if len(df[categorical_columns[i]].value_counts()) == 2:
            categorical_columns_binary.append(categorical_columns[i])

    # Use new filled list with column names, from
    # filtered incoming dataframe, to create dummies
    categorical_columns_binary_dummies = pd.get_dummies(df[categorical_columns_binary],drop_first=True)

    # Filtering list into 2 of 2 types of categorical columns:
    # e.g. MULTIVARIATE
    #-------------------------------------------------------------------------------------------------------

    # Empty list to hold categorical columns with MULTIVARIATE values
    categorical_columns_not_binary = []
    
    # Loop to search MULTIVARIATE values in categorical column
    for i in range(len(categorical_columns)):
        if len(df[categorical_columns[i]].value_counts()) > 2:
            categorical_columns_not_binary.append(categorical_columns[i])

    # Use new filled list with column names, from
    # filtered incoming dataframe, to create dummy column dataframes
    categorical_columns_not_binary_dummies = pd.get_dummies(df[categorical_columns_not_binary],drop_first=True)

    # Use both sets of dummy column dataframes to concatenate them
    # to main dataframe:

    df = pd.concat([df, categorical_columns_binary_dummies], axis=1)
    df = pd.concat([df, categorical_columns_not_binary_dummies], axis=1)
    return df